AllCops:
  Exclude:
    - 'spec/dummy/**/*'
    - 'spec/script/**/*'
    - 'bin/{rails,rake}'
    - !ruby/regexp /old_and_unused\.rb$/

Metrics/BlockLength:
  Max: 110

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Metrics/ModuleLength:
  Max: 120

Style/Documentation:
  Enabled: false
